# This is a basic workflow that is manually triggered

name: Create new Article

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      endpoint:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Endpoint'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.actor,
              repo: context.repo.repo,
              ref: "refs/heads/${{ github.event.inputs.endpoint }}",
              sha: context.sha
            })
  directory:
    needs: branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: branch } = await github.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "${{ github.event.inputs.endpoint }}"
            })

            const { data } = await github.git.createBlob({
              owner: context.actor,
              repo: context.repo.repo,
              content: ""
            })

            await github.git.createCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              message: "Initialize file",
              tree: data.sha,
              parents: [branch.commit.sha]
            })
