name: Storybook Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm ci
      - run: npm run storybook:build

      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run storybook:deploy
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
